name: opt_w_dl
channels:
  - pytorch
dependencies:
  - python=3.6
  - pyyaml
  - pytorch=1.0.0
  - numpy=1.15.4
  - pandas=0.23.4
  - h5py=2.9.0
  - tqdm=4.28.1
  - matplotlib=3.0.2
  - seaborn=0.9.0
  - scipy=1.1.0
  - scikit-learn=0.20.2
  - requests=2.21.0
  - ipywidgets=7.4.2
  # emacs bound
  - jedi=0.13.2
  - autopep8=1.4.3
  - flake8=3.6.0
  - yapf=0.25.0
  - pylint=2.2.2
